import { HStack, Stack, Box, Heading, Text} from '@chakra-ui/react'
import Head from 'next/head'
import React from 'react'
import Navbar from '../components/Navbar'
import Image from 'next/image'

 function Home() {
  return (
    <>
      <Head>
        <title>Projeto usando Next.js e Chakra UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
       <Navbar/>

       {/* Utilizando o Stack - para empilhar o elemento BOX na direção vertical */}
       {/* Criando Caixa de Texto utilizando o elemento BOX*/}

       <Stack backgroundColor={'background'} direction={['column', 'row']} spacing='24px'>
         <Box w='full' h='500px'>
          {/* Adicionando o conteúdo da função StackEx */}
          <StackEx/>
         </Box>
         <Box w='full' h='500px'> 
         <Image src="/img/fundoA.png" alt="logo" width={10000}  height={250}/> 
         </Box>
       </Stack>

      </main>
    </>
  )  
}

/* Função que passa as propriedades para construção do TEXTO */
function Feature({ title, desc, ...rest }: {
  title: string;
  desc: string;
  rest: string;
}): JSX.Element {

  return (
    <Box p={5} shadow='md' borderWidth='1px' {...rest}>
      <Heading fontSize='xl'>{title}</Heading>
      <Text mt={4}>{desc}</Text>
    </Box>
  )
  }

/* Adicionando o TEXTO */
/* Utilizando o HStack para empilhar os elementos do texto na direção horizontal */
  function StackEx() {
  return (
    <HStack spacing={8} padding={8}>
      <Feature
        title='Como Funciona ?'
        desc='A SOLUPET é um sistema onde o TUTOR pode acessar as  informações de saúde do seu animalzinho pós consulta.
        Logo após o animal ser registrado no sistema pelo Médico Veterinário, o dono do animal poderá fazer o login com os dados que foram criados na consulta, podendo assim ter acesso as informações. Ele pode acessar as clinicas mais próximas contendo avaliações, agendar consultas e imprimir carteira de vacinação e histórico clínico do seu Pet.
        O sistema abrange também auxilio ao  MÉDICO VETERINÁRIO, podendo ter acesso ao histórico clínico dos pacientes. 
        Durante a consulta, o Médico consegue realizar o cadastro do animal no sistema e também acessar cadastros já existentes. Ele pode editar o histórico clínico do paciente adicionando informações atuais, editar carteira de vacinação, agendar retorno e também cadastrar sua própria clínica.' rest={''}      
      />
    </HStack>
  )
}

export default Home;







